### PR TITLE
Registration functionality

### PR DESCRIPTION
**Pull request by wley3337**
Worked on adding actions/reducers to connect with the backend. 

Made step1 and step2 controlled forms with state for clearer processing of the forms and what we have when ( this may not have been necessary ) 

Some todos after this is go through and add validation to the fields on presence. i wasn't sure how to do that with ant design when controlled and would love some feedback on that and anything else you all see.
Also made some of the drop downs into check boxes (radio esk) buttons to be sure they have a deliberate value although not sure where to start that off. Especially for the `have you had a conviction bit`.

TIL: All our phone numbers need to have a valid country code, area code, and exchange or will be rejected on the back end. 

Debt tickets on this: [push users back to update the phone number if it's invalid](https://app.zenhub.com/workspaces/vbb-portal-frontend-5fcec904902b1d0016312d27/issues/villlagebookbuilders/frontend-vbb-portal/63)

### CODE REVIEW

**Comment by NickFoden** [comment]
Small thing if making any changes, is to change 
`<Form` to a `<div`  here, since each Step is already a `<Form` this should clear the nested form warning. 
https://github.com/VilllageBookBuilders/frontend-vbb-portal/blob/2e908aae8de95600b4031f67eebfefb2d5a6147a/src/components/registration/MasterForm.js#L70

**Comment by NickFoden** [comment]
Think this looks good!  Kinda thinking that we can "disable" the next button whenever the current step is invalid, and this function could also set the error state, so when you click "next" it lights up the invalid fields with red border and maybe a message or such. I'm a fan of controlled fields, esp since we have it piped into redux, so we can easily populate values in future when people edit or come back or left off halfway or such.

**Comment by marybees** [comment]
Looks good to me! I am still learning the ant form inputs and validation myself. Agree on the approach to get MVP first then we can look at incorporating more ant if it makes sense.

**Comment by wley3337** [comment]
Odd... it won't let me reply to your all comments...
I didn't see that comment about the <Form> --> <div> , I'll push that up real quick
Awesome! let me know what you all think on a final pass and we can merge it all in :)

**Pull request merged**
